// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKExG8tgFZczz0cY3uHBb9c3GowHthfE0',
    appId: '1:446529849084:web:2573b9c258ea8206d6b979',
    messagingSenderId: '446529849084',
    projectId: 'todo-firebase-1june',
    authDomain: 'todo-firebase-1june.firebaseapp.com',
    storageBucket: 'todo-firebase-1june.appspot.com',
    measurementId: 'G-9F57PH1XGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxumJYGYa7n9lgegc9C65rQozWy9x1j_g',
    appId: '1:446529849084:android:0a65250e069ec3f7d6b979',
    messagingSenderId: '446529849084',
    projectId: 'todo-firebase-1june',
    storageBucket: 'todo-firebase-1june.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIlioWtgWeDRNoBViS9GJcNsnzV15ywNo',
    appId: '1:446529849084:ios:c0e70a61929c3c7ed6b979',
    messagingSenderId: '446529849084',
    projectId: 'todo-firebase-1june',
    storageBucket: 'todo-firebase-1june.appspot.com',
    iosBundleId: 'com.example.todoFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIlioWtgWeDRNoBViS9GJcNsnzV15ywNo',
    appId: '1:446529849084:ios:c0e70a61929c3c7ed6b979',
    messagingSenderId: '446529849084',
    projectId: 'todo-firebase-1june',
    storageBucket: 'todo-firebase-1june.appspot.com',
    iosBundleId: 'com.example.todoFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKExG8tgFZczz0cY3uHBb9c3GowHthfE0',
    appId: '1:446529849084:web:4c8eb782f1fe8253d6b979',
    messagingSenderId: '446529849084',
    projectId: 'todo-firebase-1june',
    authDomain: 'todo-firebase-1june.firebaseapp.com',
    storageBucket: 'todo-firebase-1june.appspot.com',
    measurementId: 'G-4VPG6W6NBV',
  );
}
